spring.application.name=vuelos
spring.datasource.url=jdbc:postgresql://localhost:"ingrese su numero de puerto"/sistema_vuelos
spring.datasource.username=postgres
spring.datasource.password="ingrese su contraseña"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
